package ThinkDaily;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class ReportsService {

    private final Connection conn;

    // metadata (like UML)
    private final String title;
    private final LocalDateTime generatedAt;
    private final String generatedBy; // accounts.username (ADMIN)

    public ReportsService(Connection conn) {
        this.conn = conn;
        this.title = "Dashboard Report";
        this.generatedAt = LocalDateTime.now();
        this.generatedBy = fetchAdminUsername(); // ✅ auto from DB
    }

    public JComponent generateReport(String reportType) {
    JTabbedPane tabs = new JTabbedPane();

    tabs.addTab("Overview", new JScrollPane(buildOverviewTable()));
    tabs.addTab("By Category", new JScrollPane(buildCategoryTable()));
    tabs.addTab("By Users", new JScrollPane(buildUsersStatsTable()));
    tabs.addTab("By Questions", new JScrollPane(buildQuestionsStatsTable())); // ✅ NEW

    
    return tabs;
}


    private JTable buildOverviewTable() {

    int totalUsers = 0;
    int totalQuestions = 0;
    int activeToday = 0;
    int totalCategories = 0;

    try {
        // Total active players
        String q1 = """
            SELECT COUNT(*) 
            FROM users u
            JOIN accounts a ON u.account_id = a.account_id
            WHERE a.role = 'PLAYER' AND a.is_active = 1
        """;
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(q1)) {
            if (rs.next()) totalUsers = rs.getInt(1);
        }

        // Active questions
        String q2 = "SELECT COUNT(*) FROM questions WHERE is_active = TRUE";
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(q2)) {
            if (rs.next()) totalQuestions = rs.getInt(1);
        }

        // Active users today
        String q3 = """
            SELECT COUNT(DISTINCT user_id)
            FROM user_responses
            WHERE DATE(answered_at) = CURDATE()
        """;
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(q3)) {
            if (rs.next()) activeToday = rs.getInt(1);
        }

        // Total categories
        String q4 = "SELECT COUNT(*) FROM categories";
        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(q4)) {
            if (rs.next()) totalCategories = rs.getInt(1);
        }

    } catch (SQLException e) {
        System.out.println("Overview report error: " + e.getMessage());
    }

    DateTimeFormatter formatter =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    String[] cols = {"Metric", "Value"};
    Object[][] data = {
            {"Report Title", title},
            {"Generated At", generatedAt.format(formatter)},
            {"Generated By", generatedBy},
            {"Total Users (Players Only)", totalUsers},
            {"Total Questions (Active)", totalQuestions},
            {"Active Today", activeToday},
            {"Total Categories", totalCategories}
    };

    JTable table = new JTable(new DefaultTableModel(data, cols) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    });

    table.setRowHeight(22);
    return table;
}

private JTable buildQuestionsStatsTable() {
    QuestionStats[] list = QuestionStats.generate(conn);

    String[] cols = {
            "Question ID",
            "Question Text",
            "Times Answered",
            "Times Correct",
            "Accuracy %"
    };

    Object[][] data = new Object[list.length][cols.length];

    for (int i = 0; i < list.length; i++) {
        QuestionStats q = list[i];

        int answered = q.getTimesAnswered();
        int correct = q.getTimesCorrect();

        double accuracy = answered > 0
                ? (correct * 100.0 / answered)
                : 0.0;

        data[i][0] = q.getQuestionId();
        data[i][1] = q.getQuestionText();
        data[i][2] = answered;
        data[i][3] = correct;
        data[i][4] = String.format("%.1f%%", accuracy);
    }

    JTable t = new JTable(new javax.swing.table.DefaultTableModel(data, cols) {
        @Override
        public boolean isCellEditable(int r, int c) {
            return false;
        }
    });

    t.setRowHeight(22);
    t.getColumnModel().getColumn(1).setPreferredWidth(350); // question text wider
    return t;
}

    private JTable buildCategoryTable() {
    CategoryStats[] list = CategoryStats.generate(conn);

    String[] cols = { "Category ID", "Category Name", "Total Questions", "% of All Questions" };

    Object[][] data = new Object[list.length][cols.length];
    for (int i = 0; i < list.length; i++) {
        CategoryStats cs = list[i];
        data[i][0] = cs.getCategoryId();
        data[i][1] = cs.getCategoryName();
        data[i][2] = cs.getQuestionCount();
        data[i][3] = String.format("%.1f%%", cs.getQuestionPercent());
    }

    JTable t = new JTable(new DefaultTableModel(data, cols) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    });
    t.setRowHeight(22);
    return t;

    }
    
    private JTable buildUsersStatsTable() {
    UserStats[] list = UserStats.generate(conn);

    String[] cols = {
            "User ID",
            "Username",
            "Total Points",
            "Answered",
            "Correct"
    };

    Object[][] data = new Object[list.length][cols.length];

    for (int i = 0; i < list.length; i++) {
        UserStats u = list[i];
        data[i][0] = u.getUserId();
        data[i][1] = u.getUsername();
        data[i][2] = u.getTotalPoints();
        data[i][3] = u.getTotalAnswered();
        data[i][4] = u.getTotalCorrect();
    }

    JTable t = new JTable(new javax.swing.table.DefaultTableModel(data, cols) {
        @Override public boolean isCellEditable(int r, int c) { return false; }
    });

    t.setRowHeight(22);
    return t;
}


    private String fetchAdminUsername() {
        if (conn == null) return "ADMIN";
        try {
            String sql = """
                SELECT username
                FROM accounts
                WHERE role = 'ADMIN' AND is_active = 1
                ORDER BY account_id ASC
                LIMIT 1
            """;
            try (PreparedStatement ps = conn.prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return rs.getString("username");
            }
        } catch (SQLException e) {
            System.out.println("fetchAdminUsername error: " + e.getMessage());
        }
        return "ADMIN";
    }

    // Optional getters (if you want for documentation/testing)
    public String getGeneratedBy() { return generatedBy; }
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public String getTitle() { return title; }
}
